### ISSUE TITLE
Repeat data falling on tile edges

### ISSUE THREAD

**Issue by migurski** [sharedstreets/sharedstreets-builder#14]
The z12 tiles let data fall through the cracks, such as this [sample location on the border between `12/656/1582` and `12/657/1582`](https://www.openstreetmap.org/#map=16/37.8190/-122.2534):

<img width="965" alt="screen shot 2018-04-24 at 9 48 51 am" src="https://user-images.githubusercontent.com/58730/39201776-de2418be-47a4-11e8-88ef-c10a79fb37bb.png">

Ideally each z12 tile should include enough data to overlap slightly with its neighbor so that a seamless map can be generated.

**Comment by migurski** [comment]
Some additional details and comment on this: we’re generating GeoJSON tiles and using them in the browser based on higher zoom level tiles. The ones here are being displayed with `clip: true`. Each geometry is guaranteed to show up exactly once, so it has to "choose" a tile. We could generate our tiles by inspecting neighbors, though that would greatly balloon the amount of time needed. Another option would be for us to populate a database from the ShSt z12 tiles, and use that instead. This is less-good, because we like the ability to reach back to S3 for a reliable source of worldwide data.

**Comment by kpwebb** [comment]
@migurski  this is something we've been grappling with. But it looks like this is actually a bug. Our current approach is (supposed to be!) that we include the reference in every tile that contains a location reference point. So the ShSt ref that spans a tile boundary should should show up in the tile of origin and destination. For geometries we're including them in every tile that contains a coordinate point. But it looks like this isn't working as planned.

I'll investigate, but I'm curious if this approach (if working) would address your need?

**Comment by kpwebb** [comment]
Actually -- can you share the the geoJSON for these tiles? I'm not how this is happening:

<img width="107" alt="screen shot 2018-04-25 at 9 58 32 am" src="https://user-images.githubusercontent.com/43052/39250754-9261c8ce-486f-11e8-8fb9-cd67b33d8f91.png">

The builder only works with complete intersection to intersection features, so I'm wondering if the clipping at the tile boundary in that image is happening elsewhere. Maybe inside Mapbox GL's geojson processor?

Either way I might be misunderstanding the problem, but just want to make sure I get where things are being clipped.

**Comment by kpwebb** [comment]
<ignore previous question about clipping, i just reread your comment about about the "clip: true" feature>

**Comment by kpwebb** [comment]
@migurski  can you send me the geoJson output for 12/656/1582 and 12/657/1582 tiles independently?

**Comment by migurski** [comment]
Sure; I zoomed in a little to show z17 tiles that we’re using in the image above, see this gist: https://gist.github.com/migurski/b8efedbe956fecfed62d8ec1ea98f41c

The eastbound lanes of 580 are present in one, and the westbound lanes in the other. I’m using Leaflet GeoJSON to make the screenshot above.

**Comment by kpwebb** [comment]
Ok! So if tile-spanning features were present in both tiles, that would fix this, correct?  The client then clips or deduplicates.

**Comment by kpwebb** [comment]
Great! So that's what should already be happening with the existing tiles -- now I just need to figure out why it isn't...Stay tuned!

**Comment by kpwebb** [comment]
Ok! Pushed tiles that should fix this at:

tiles.sharedstreets.io/osm/planet-180430/...

Based on review so far, this error only effected the geometries (ShSt references should have been in any tile with a LR point). 

Starting with planet-180430 geoms should show up in any tile where the geom has a coordinate. In theory there could be geom that cross a tile without any coordinates in tile that's crossed. 

I can see a couple options for fixing that (include all tiles in the x-y range between min tile and max tile, or find the intersection of the geom bounding box with tiles). If this becomes a problem happy to explore those options in more depth.

Previous tile builds still use the old version and geoms will only show up in the tile where coordinate[0] lives.

**Comment by kpwebb** [comment]
@migurski just wanted to check and see if this fixed error above...

**Comment by migurski** [comment]
Thanks Kevin — I haven't yet had a chance to test this. I’ll try today and respond here.

**Comment by migurski** [comment]
Much better:

<img width="953" alt="screen shot 2018-05-09 at 10 52 18 am" src="https://user-images.githubusercontent.com/58730/39830685-0bb9f680-5377-11e8-8077-30c8eb2a4e32.png">

**Comment by kpwebb** [comment]
Woo! thanks for catching this... and per above, feel free to re-open if we need to include tiles that intersect with line segments, but don't contain any actual coordinates from the line. 

Closing for now.
