### ISSUE TITLE
Reference Id tests for bare minimum inputs

### ISSUE THREAD

**Issue by DenisCarriere** [sharedstreets/sharedstreets-builder#3]
Are there any simple tests to produce `geometryId`, `backreferenceId` & `forwardId`?

For example, if the bare minimum inputs would be:

```json
{
    "start": [-74.003388, 40.634538],
    "end": [-74.004107, 40.63406],
    "bearing": 228.890377
}
```
Having unit tests in Java/NodeJS & other languages, should all return the same reference Ids.

CC: @kpwebb

**Comment by kpwebb** [comment]
added beginning of test framework in v0.1.2, but more improvements to test framework needed!

https://github.com/sharedstreets/sharedstreets-builder/commit/be7bdc0ea261a9536eef8f9d11595143e241c131#diff-9019388c741d3a9386e82f175f37b7fcR14

**Comment by DenisCarriere** [comment]
The Java builder & Javascript library lines up with each other, so no need to add extra tests in the Java builder repo.
