### ISSUE TITLE
sharedstreets-builder-0.1-preview.jar doesn't exist

### ISSUE THREAD

**Issue by 3vivekb** [sharedstreets/sharedstreets-builder#6]
sharedstreets-builder-0.1-preview.jar doesn't exist after building thus it's unclear how to test build from a pbf.

**Comment by 3vivekb** [comment]
Nevermind they are in the [releases](https://github.com/sharedstreets/sharedstreets-builder/releases).

**Comment by kpwebb** [comment]
@3vivekb As an FIY, you shouldn't need to use the builder. We've created a global tile set from OSM and are developing a set of conflation tools for GIS that should support other data sets.
