### ISSUE TITLE
Exclude Parking Lots?

### ISSUE THREAD

**Issue by 3vivekb** [sharedstreets/sharedstreets-builder#8]
Do you want to try to exclude micro-mapped parking lots?

![image](https://user-images.githubusercontent.com/4524205/36927624-78778176-1e33-11e8-957a-3dfbbe0789c7.png)

**Comment by kpwebb** [comment]
@3vivekb let's try and do this using the "service=parking_asle" tag. I fear that OSM isn't consistently mapping these features, but we can give it a shot!

I'd also like to try and map private driveways separately from service roads via "service=driveway", but from our experimentation very driveways use this tag.

**Comment by kpwebb** [comment]
Addressed in #11
