### ISSUE TITLE
add street name to metadata tiles

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/sharedstreets-builder#9]
Proposed approach:

Add name field to OSMMetadata and WaySection elements. If only one version of the street name for all way sections the name goes in OSMMetadata otherwise we store each version in the WaySection and leave OSMMetadata blank. Open to suggestions on how to do this but goal is not to have tons of duplicate version of the street name for each reference.

**Comment by kpwebb** [comment]
add changes to builder in #11 
Also updated proto buf spec to include names in sharedstreets/sharedstreets-ref-system/pull/18

**Comment by DenisCarriere** [comment]
👍 Names would be good, I doubt there will be a way to prevent duplicate names per each `Reference`. Including a `name` field seems very valuable.

**Comment by migurski** [comment]
This approach makes sense to me as well.
